import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { ChevronDown, ChevronRight, Quote, ExternalLink } from 'lucide-react';

interface CitationsListProps {
  citations: Record<string, string | { text: string; link?: string }>;
  username: string;
}

export const CitationsList: React.FC<CitationsListProps> = ({ citations = {}, username }) => {
  const [isOpen, setIsOpen] = useState(false);

  const formatCitation = (text: string) => {
    // Truncate long citations for better display
    if (text.length > 200) {
      return text.substring(0, 200) + '...';
    }
    return text;
  };

  const citationEntries = Object.entries(citations).filter(([_, value]) => value && (typeof value === 'string' ? value.trim() : value.text && value.text.trim()));

  if (citationEntries.length === 0) {
    return null;
  }

  return (
    <Card className="w-full max-w-4xl mx-auto animate-fade-in">
      <Collapsible open={isOpen} onOpenChange={setIsOpen}>
        <CollapsibleTrigger asChild>
          <CardHeader className="cursor-pointer hover:bg-secondary/50 transition-colors">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <Quote className="h-5 w-5 text-reddit-orange" />
                <CardTitle className="text-lg">
                  Supporting Evidence ({citationEntries.length} citations)
                </CardTitle>
              </div>
              <div className="flex items-center gap-2">
                <Badge variant="secondary" className="text-xs">
                  From u/{username}'s posts
                </Badge>
                {isOpen ? (
                  <ChevronDown className="h-5 w-5 text-muted-foreground" />
                ) : (
                  <ChevronRight className="h-5 w-5 text-muted-foreground" />
                )}
              </div>
            </div>
          </CardHeader>
        </CollapsibleTrigger>

        <CollapsibleContent>
          <CardContent className="pt-0 space-y-6">
            <p className="text-sm text-muted-foreground mb-4">
              These are actual quotes from the Reddit profile that helped generate each personality trait:
            </p>
            <div className="grid gap-6">
              {citationEntries.map(([trait, citation], index) => {
                const citationText = typeof citation === 'string' ? citation : citation.text;
                const citationLink = typeof citation === 'object' && citation.link ? citation.link : null;
                return (
                  <div key={index} className="border border-border rounded-xl p-6 bg-card hover:bg-secondary/30 transition-colors space-y-3">
                    <div className="flex items-center justify-between mb-2">
                      <Badge variant="outline" className="capitalize text-base px-3 py-1">
                        {trait.replace(/_/g, ' ')}
                      </Badge>
                      {citationLink && (
                      <Button 
                        variant="ghost" 
                        size="sm"
                          onClick={() => window.open(citationLink, '_blank')}
                        className="text-xs"
                      >
                        <ExternalLink className="h-3 w-3 mr-1" />
                          View Source
                      </Button>
                      )}
                    </div>
                    <blockquote className="border-l-4 border-reddit-orange pl-4 italic text-muted-foreground text-base">
                      "{formatCitation(citationText)}"
                    </blockquote>
                  </div>
                );
              })}
            </div>
            <div className="pt-6 border-t border-border mt-6">
              <div className="flex items-center justify-between text-xs text-muted-foreground">
                <span>Citations are extracted from recent Reddit activity</span>
                <span>Generated by AI • Not 100% accurate</span>
              </div>
            </div>
          </CardContent>
        </CollapsibleContent>
      </Collapsible>
    </Card>
  );
};