import React from 'react';
import { Button } from '@/components/ui/button';
import { Download, FileText } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface PersonaData {
  name: string;
  age: string;
  location: string;
  occupation: string;
  interests: string[];
  personality: string[];
  political_view: string;
  lifestyle: string;
  communication_style: string;
  values: string[];
}

interface DownloadButtonProps {
  persona: PersonaData;
  username: string;
  citations: Record<string, string>;
}

export const DownloadButton: React.FC<DownloadButtonProps> = ({ persona, username, citations }) => {
  const { toast } = useToast();

  const generateTextContent = () => {
    const currentDate = new Date().toLocaleDateString();
    
    return `Reddit Persona Analysis for u/${username}
Generated on: ${currentDate}
Generated by: AI Reddit Persona Generator

======================================
PERSONA SUMMARY
======================================

Name: ${persona.name}
Age: ${persona.age}
Location: ${persona.location}
Occupation: ${persona.occupation}

======================================
PERSONALITY TRAITS
======================================
${persona.personality.join(', ')}

======================================
INTERESTS & HOBBIES
======================================
${persona.interests.join(', ')}

======================================
CORE VALUES
======================================
${persona.values.join(', ')}

======================================
COMMUNICATION STYLE
======================================
${persona.communication_style}

======================================
POLITICAL VIEWS
======================================
${persona.political_view}

======================================
LIFESTYLE
======================================
${persona.lifestyle}

======================================
SUPPORTING EVIDENCE
======================================

${Object.entries(citations)
  .filter(([_, value]) => value && value.trim())
  .map(([trait, citation]) => `${trait.toUpperCase().replace(/_/g, ' ')}:\n"${citation}"\n`)
  .join('\n')}

======================================
DISCLAIMER
======================================
This persona was generated by AI based on public Reddit posts and comments.
It is an approximation and may not reflect the actual person accurately.
This analysis is for entertainment and educational purposes only.

Source Profile: https://reddit.com/user/${username}
Generated by: AI Reddit Persona Generator
`;
  };

  const handleDownload = () => {
    try {
      const content = generateTextContent();
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      
      const link = document.createElement('a');
      link.href = url;
      link.download = `reddit-persona-${username}-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      URL.revokeObjectURL(url);
      
      toast({
        title: "Download successful!",
        description: `Persona for u/${username} has been downloaded as a text file.`
      });
    } catch (error) {
      toast({
        title: "Download failed",
        description: "There was an error generating the download file.",
        variant: "destructive"
      });
    }
  };

  return (
    <div className="flex justify-center animate-fade-in">
      <Button
        onClick={handleDownload}
        variant="outline"
        size="lg"
        className="gap-3 px-8 py-6 text-lg font-medium border-2 border-reddit-orange text-reddit-orange hover:bg-reddit-orange hover:text-white transition-all duration-300 rounded-xl"
      >
        <Download className="h-5 w-5" />
        Download Persona Report
        <FileText className="h-5 w-5" />
      </Button>
    </div>
  );
};